issues:
  exclude-rules:
    - linters:
      - gosimple
      text: "S1002: should omit comparison to bool constant"
    - linters:
      - revive
      text: "exported: exported const"
    # TODO(hugoShaka): Remove once https://github.com/dominikh/go-tools/issues/1294 is fixed
    - linters:
      - unused
      path: 'operator/controllers/resources/(.+)_controller_test\.go'
    # TODO(codingllama): Remove ignore after the new golangci-lint image lands.
    # For some reason this particular files causes problems between different
    # goimports versions.
    - path: lib/services/role_test.go
      linters:
      - goimports
  exclude-use-default: true
  max-same-issues: 0
  max-issues-per-linter: 0

linters-settings:
  depguard:
    list-type: denylist
    include-go-root: true # check against stdlib
    packages-with-error-message:
    - io/ioutil: 'use "io" or "os" packages instead'
    - github.com/golang/protobuf: 'use "google.golang.org/protobuf"'
    - github.com/siddontang/go-log/log: 'use "github.com/sirupsen/logrus" instead'
    - github.com/siddontang/go/log: 'use "github.com/sirupsen/logrus" instead'
    - go.uber.org/atomic: 'use "sync/atomic" instead'
  errcheck:
    check-type-assertions: true
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/gravitational/teleport) # Custom section: groups all imports with the specified Prefix.
    skip-generated: true # Skip generated files.
    custom-order: true # Required for "sections" to take effect.
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - commentedOutCode
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
  misspell:
    locale: US
  nolintlint:
    allow-unused: true # Enabled because of conditional builds / build tags.
    require-explanation: true
    require-specific: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  funlen:
    lines: 100
    statements: 50

output:
  uniq-by-line: false

run:
  issues-exit-code: 1
  skip-dirs:
    - playground
    - fixtures
    - testdata
  # skip-dirs-use-default: false
  timeout: 5m
  go: '1.19'

linters:
  disable-all: true
  enable:
    #/- bodyclose
    #- deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    #- exhaustive
    - exportloopref
    - funlen
    - goconst
    - gocognit
    - gocritic
    - gofmt
    #- goimports
    #- gomnd
    - gocyclo
    - goprintffuncname
    - gosec
    #/- gosimple
    - govet
    - ineffassign
    #/- interfacer
    #- maligned
    - misspell
    #- nolintlint
    #- nakedret
    - prealloc
    - predeclared
    - revive
    #/- staticcheck
    #- structcheck
    #/- stylecheck
    #- thelper
    #/- tparallel
    #- typecheck
    - unconvert
    #- unparam
    - varcheck
    - whitespace
    #- wsl

#linters:
#  enable:
#    - bodyclose
#    - dogsled
#    - errcheck
#    - errname
#    - errorlint
#    #    - exhaustive
#    #    - exportloopref
#    #    - funlen
#    #    - gochecknoinits
#    #    - goconst
#    #    - gocritic
#    #    - gocyclo
#    #    - gofmt
#    # - golint
#    - gocritic
#    # - goimports
#    - gosec
#    - stylecheck
#    - unconvert
#  disable:
#    - maligned
#    - unparam
#    - lll
#    - gochecknoinits
#    - gochecknoglobals
#    - dupl
#    - deadcode
#    - nakedret
#    - structcheck
#
#  enable:
#    - bodyclose
#    - deadcode
#    - dogsled
#    - dupl
#    - errcheck
#    - errname
#    - errorlint
#    - exhaustive
#    - exportloopref
#    - funlen
#    - gochecknoinits
#    - goconst
#    - gocritic
#    - gocyclo
#    - gofmt
#    - goimports
#    - gomnd
#    - goprintffuncname
#    - gosec
#    - gosimple
#    - govet
#    - ifshort
#    - ineffassign
#    # - lll
#    - makezero
#    - misspell
#    - nakedret
#    - noctx
#    - nolintlint
#    - revive
#    - staticcheck
#    - structcheck
#    - stylecheck
#    # - testpackage
#    - typecheck
#    - unconvert
#    - unparam
#    - unused
#    - varcheck
#    - whitespace

